### ISSUE TITLE
TLD support for url validator

### ISSUE THREAD

**Issue by krachtstefan** [franckverrot/activevalidators#100]
Thanks for this repo, it's a great validation resource!

I just have on suggestion. It would be great to make it possible to decide whether a url is allowed to have a tld or not. 

`http://localhost` is a valid url for sure, but most user inputs should force a tld to prevent typos like `http://mywebsitecom`

Or is there already an option which I didn't notice?

**Comment by franckverrot** [comment]
Hi again, and thanks!

So no there isn't any option available right now to do what you suggest, but we coud build something.

Would you like to try submitting a PR and we could start the discussion from there? Or we could also discuss here and see what can be done for your use-case?

Thanks again!

**Comment by krachtstefan** [comment]
Thanks for your reply @franckverrot. I just made [a pull request](https://github.com/franckverrot/activevalidators/pull/102). I tried my best to make meaningful comments but don't hesitate to ask, if you have any questions.

**Comment by franckverrot** [comment]
Thanks, closing this in favor of the PR.
