### ISSUE TITLE
Is 'username@domain.com, anything' a valid email?!

### ISSUE THREAD

**Issue by stgeneral** [franckverrot/activevalidators#51]
Email validator assumes that `username@domain.com, anything` is valid email.

**Comment by supairish** [comment]
@franckverrot I'm seeing a similar issue, and I'm confused on what validation is happening.  So does this mean the ActiveValidators email validation doesn't actually validate the email format?  If the mail gem just "fixes" the problem with the provided string but we aren't updating the attribute provided, what are we actually validating?  Does the README need to be updated to reflect this?

**Comment by stgeneral** [comment]
I think that email validator should have an option to validate by regexp. Something like this:
```ruby
class User
  validates :email_address, :email => { :regexp => true } # use build some build in regexp
  validates :email_address, :email => { :regexp => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/  } # option to pass custom regexp
end
```

Regexp was taken from the Devise code: https://github.com/plataformatec/devise/blob/d3d9fba201e3b23361f68ff44e96a6dbf4492afc/lib/devise.rb#L124

**Comment by franckverrot** [comment]
@supairish Do you mind providing the mail addresses you're failing to validate?

I investigated a bit and indeed, the README is obsolete... but the validation does seem work OK.

@stgeneral You might want to use the `regexp` validator instead of the `email` one in that case :-)

**Comment by supairish** [comment]
@franckverrot  We had a user provide "lsd@sdsh.co," and it was not caught.  But we're also using an old version of this gem "2.1.0".  I'll have to give it a go with the latest.

**Comment by franckverrot** [comment]
Alright. Please keep me posted if you see anything weird, I'll be glad to
help!

On Tue, Feb 3, 2015 at 11:52 PM, Chris Irish <notifications@github.com>
wrote:

> @franckverrot <https://github.com/franckverrot> We had a user provide "
> lsd@sdsh.co," and it was not caught. But we're also using an old version
> of this gem "2.1.0". I'll have to give it a go with the latest.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/franckverrot/activevalidators/issues/51#issuecomment-72753363>
> .
>



-- 
Franck Verrot
https://github.com/franckverrot
https://twitter.com/franckverrot
