### ISSUE TITLE
http:bla passes url validation

### ISSUE THREAD

**Issue by stevendelarwelle** [franckverrot/activevalidators#82]
http:bla passes url validation

**Comment by franckverrot** [comment]
Hi @stevendelarwelle,

You can restrict/specify the schemes you only want to support using this notation:

```ruby
validates :your_url, url: { protocols: %w(http https) }
```

Here is the full-documentation for the `UrlValidator`: http://www.rubydoc.info/gems/activevalidators/ActiveModel/Validations/UrlValidator

Please re-open the ticket if this doesn't fix your problem. 

And thanks for using this gem!
Franck
