### ISSUE TITLE
Default error messages

### ISSUE THREAD

**Issue by dmxhZGp1c2hh** [franckverrot/activevalidators#84]
I tried to use email and phone validations and found out that message option is required.

In docs it said that gem can be used like this:

```ruby
validates :email, presence: true, email: true
```

In this case messages will be `nil`, so model would not be valid, but there will be no message with explanation why.

Can be fixed like this:

```ruby
validates :email, presence: true, email: { message: 'not valid' }
```

It's kinda redundant in my opinion.

Mby we need to add default messages for validators?

**Comment by franckverrot** [comment]
The validators rely on ActiveModel validations, and will require one to use its i18n-based mechanism (`config/locales/...`). It's maybe a lack in the documentation by itself and will accept a PR fixing such a thing (at least, something that explains how one's supposed to format them, even if it's redundant with ActiveModel's documentation).

Thanks for reporting this, I hope this helps, WDYT?
