### ISSUE TITLE
initializer warning but I have this setup correctly

### ISSUE THREAD

**Issue by chrishough** [franckverrot/activevalidators#85]
In my `config/active_validators.rb` file:
```
ActiveValidators.activate(:url, :slug)
```
In my model:
```
  validates :logo_cdn_url,
            presence: true,
            url: true,
            length: { maximum: 245 }

  validates :slug, presence: true, slug: true
```
Error Messages:
<img width="1086" alt="screen shot 2016-05-26 at 5 52 39 pm" src="https://cloud.githubusercontent.com/assets/744056/15594484/abe224dc-236a-11e6-8c0d-071136b18811.png">

**Comment by franckverrot** [comment]
Update the gem, this should go away.

**Comment by chrishough** [comment]
Thank you that fixed it.  I think the other warning `default_options has been deprecated, use options` is coming from something else.
