### ISSUE TITLE
Date validation breaks, maybe because of ActiveAdmin datepicker

### ISSUE THREAD

**Issue by Koroeskohr** [franckverrot/activevalidators#94]
Using Ruby 2.3.1, Rails 4.2.6, ActiveValidators 4.0.0

I have a `PressRelease` model that has a `datetime` field, `released_at`. When using ActiveAdmin's datepicker, my date validation (that looks like this : )
```ruby
class PressRelease < ActiveRecord::Base
  validates :released_at, presence: true, date: { before: lambda { Time.now }, after: lambda { 50.years.ago } }
end
```
breaks and throws an `ArgumentError : wrong number of arguments (given 1, expected 0)`.

I also use the URL validation, no problem with this one. 

Full trace : 
[trace.txt](https://github.com/franckverrot/activevalidators/files/373125/trace.txt)

**Comment by penman** [comment]
This error comes from your `before:` and `after:` lambdas.
Using a lambda means that any the number of arguments you've specified is enforced with an exception.
The date validator [passes an argument](https://github.com/codegram/date_validator/blob/0a1f7aecac9c8afe3967dd622767505df607b7e4/lib/active_model/validations/date_validator.rb#L79) to these when it calls them, which is what's causing your error.

To fix the error, change your `lambda`s to `proc`s to ignore the argument silently.

**Comment by Koroeskohr** [comment]
The documentation in the README would then be the issue here : 
```ruby
class Article
  validates :slug,            :slug => true
  validates :expiration_date, :date => {
                                          :after => lambda { Time.now },
                                          :before => lambda { Time.now + 1.year }
                                        }
end
```
