### ISSUE TITLE
[deprecated] ActiveValidators.activate is the recommended solution to require your validators. Please check instructions in the README. Thanks a lot !

### ISSUE THREAD

**Issue by Feuda** [franckverrot/activevalidators#98]
Rails 5.0.2 && ActiveValidators v3.0.0

**Comment by alyssais** [comment]
Hey! It's not entirely clear to me what problem you're having — could you explain a bit more?

3.0.0 is a very old version though — I notice the README still points to it, so I'll get that updated.

**Comment by alyssais** [comment]
For what it's worth, I made a new Rails 5.0.2 app, installed ActiveValidators 3.0.0, generated a scaffold with an email validation, and all seemed to be working fine.

**Comment by Feuda** [comment]
Hey, after updating to ActiveValidators 4.0.1, the alert disappeared, thank you
